# Generated by Django 2.1.5 on 2019-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_18_plus',
            field=models.BooleanField(default=False),
        ),
    ]
