# Generated by Django 2.1.5 on 2019-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
