# Generated by Django 2.1.5 on 2019-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190910_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
    ]
