# Generated by Django 2.1.5 on 2019-11-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_images_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_requirement', models.TextField(blank=True, null=True)),
                ('prize_image_url', models.ImageField(upload_to='images')),
                ('comp_image_video', models.FileField(blank=True, upload_to='')),
                ('no_of_winners', models.CharField(blank=True, max_length=120)),
                ('countdown_time', models.CharField(blank=True, max_length=120)),
                ('personal_msg', models.CharField(blank=True, max_length=120)),
                ('prize_delivery_time', models.CharField(blank=True, max_length=120)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_comp_post', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_option', models.ImageField(blank=True, null=True, upload_to='images/poll_option')),
                ('text_option', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PollPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(blank=True, max_length=120)),
                ('poll_end_value', models.CharField(blank=True, max_length=5)),
                ('poll_end_type', models.CharField(blank=True, max_length=120)),
                ('option_type', models.CharField(choices=[('1', 'image'), ('2', 'text')], default='1', max_length=3)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_post', to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='polloptions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option', to='posts.PollPost'),
        ),
    ]
