# Generated by Django 2.1.5 on 2019-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20191118_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpost',
            name='poll_end_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pollpost',
            name='ques',
            field=models.TextField(blank=True),
        ),
    ]
