# Generated by Django 2.1.5 on 2019-11-19 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191118_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEntryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_images', models.ImageField(upload_to='competition_prize')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compt_post_entry_images', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionPrizeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_images', models.ImageField(upload_to='competition_prize')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compt_post_images', to='posts.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='competitionpost',
            name='prize_delivery_time_type',
        ),
        migrations.RemoveField(
            model_name='competitionpost',
            name='prize_delivery_time_value',
        ),
        migrations.AddField(
            model_name='competitionpost',
            name='entry_video',
            field=models.FileField(blank=True, null=True, upload_to='competition_video'),
        ),
        migrations.AddField(
            model_name='competitionpost',
            name='prize_delivery_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionpost',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='competition_thmbnail'),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='countdown_time',
            field=models.TimeField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='polloptions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_post_options', to='posts.Post'),
        ),
    ]
