# Generated by Django 2.1.5 on 2019-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191119_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpost',
            name='entry_type',
            field=models.CharField(choices=[('1', 'image'), ('2', 'video')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
