# Generated by Django 2.1.5 on 2019-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_competitionpost_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionprizeimages',
            name='prize_images',
            field=models.ImageField(default='2', upload_to='competition_prize'),
        ),
    ]
