# Generated by Django 2.1.5 on 2019-11-20 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_competitionenteredusers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionenteredusers',
            unique_together={('post', 'entered_by')},
        ),
    ]
