# Generated by Django 2.1.5 on 2019-11-21 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20191120_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollpost',
            name='poll_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
