# Generated by Django 2.1.5 on 2019-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20191121_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpost',
            name='poll_end_type',
            field=models.CharField(blank=True, choices=[('Second', 'Second'), ('Minute', 'Minute'), ('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=50),
        ),
    ]
