# Generated by Django 2.1.5 on 2019-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20191122_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpost',
            name='poll_end_type',
            field=models.CharField(blank=True, choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=50),
        ),
    ]
