# Generated by Django 2.1.5 on 2019-11-22 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20191122_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpost',
            name='competition_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
