# Generated by Django 2.1.5 on 2019-11-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_remove_competitionpost_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionentryimages',
            name='post',
        ),
        migrations.DeleteModel(
            name='CompetitionEntryImages',
        ),
    ]
