# Generated by Django 2.1.5 on 2019-11-25 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0026_auto_20191122_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
