# Generated by Django 2.1.5 on 2019-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_saveaddressforcompetitionprize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveaddressforcompetitionprize',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
