# Generated by Django 2.1.5 on 2019-11-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_competitionwinners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionwinners',
            old_name='users',
            new_name='winners',
        ),
    ]
