# Generated by Django 2.1.5 on 2019-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20191126_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpost',
            name='enterd_by',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionpost',
            name='blog_by',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
