# Generated by Django 2.1.5 on 2019-11-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20191129_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionpost',
            old_name='enterd_by',
            new_name='entered_by',
        ),
    ]
