# Generated by Django 2.1.5 on 2019-11-29 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20191129_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_shared_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_main_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_main_post', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='posts.Post'),
        ),
    ]
