# Generated by Django 2.1.5 on 2019-12-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0035_auto_20191129_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionWinnersPrizeDeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_price_received', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersComplains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prize_delivery_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.CompetitionWinnersPrizeDeliveryStatus')),
            ],
        ),
    ]
