# Generated by Django 2.1.5 on 2019-12-10 06:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0038_auto_20191210_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post_id', 'liked_by')},
        ),
    ]
