# Generated by Django 2.1.5 on 2019-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20191210_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
