# Generated by Django 2.1.5 on 2019-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_auto_20191210_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_text',
            field=models.TextField(blank=True),
        ),
    ]
