# Generated by Django 2.1.5 on 2019-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_post_shared_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportapost',
            name='option',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportapost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
