# Generated by Django 2.1.5 on 2019-12-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.CompetitionPost'),
        ),
    ]
