# Generated by Django 2.1.5 on 2019-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='videos/')),
                ('thumb', models.FileField(null=True, upload_to='videos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
