# Generated by Django 2.1.5 on 2019-10-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupmemberlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmemberlists',
            old_name='created_by',
            new_name='user_id',
        ),
    ]
