# Generated by Django 2.1.5 on 2019-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='social_link_type',
            field=models.CharField(blank=True, choices=[('1', 'normal'), ('2', 'google'), ('3', 'twitter'), ('4', 'instagram'), ('5', 'linkedin'), ('6', 'fb')], max_length=5),
        ),
    ]
