# Generated by Django 2.1.5 on 2019-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190604_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='social_link_type',
            field=models.CharField(blank=True, choices=[('1', 'facebook'), ('2', 'google'), ('3', 'twitter'), ('4', 'instagram'), ('5', 'linkedin')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('1', 'normal'), ('2', 'fb'), ('3', 'instagram'), ('4', 'snapchat'), ('5', 'twitter'), ('6', 'google')], max_length=500),
        ),
    ]
