# Generated by Django 2.1.5 on 2019-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190618_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkexperience',
            name='location_long',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='locations_lat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
