# Generated by Django 2.1.5 on 2019-06-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190618_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkexperience',
            old_name='locations_lat',
            new_name='location_lat',
        ),
    ]
