# Generated by Django 2.1.5 on 2019-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190618_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, choices=[('1', 'android'), ('2', 'ios')], max_length=5),
        ),
    ]
