# Generated by Django 2.1.5 on 2019-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190618_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'fb'), ('3', 'instagram'), ('4', 'snapchat'), ('5', 'twitter'), ('6', 'google')], default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
