# Generated by Django 2.1.5 on 2019-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190619_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
