# Generated by Django 2.1.5 on 2019-06-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190619_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('account_type', 'social_id')},
        ),
    ]
