# Generated by Django 2.1.5 on 2019-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190620_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='current_city_lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='current_city_long',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='hometown_lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='hometown_long',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
