# Generated by Django 2.1.5 on 2019-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190620_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterests',
            name='interest_type',
            field=models.CharField(choices=[('1', 'activities'), ('2', 'hobbies'), ('3', 'music'), ('4', 'movies'), ('5', 'tv_shows'), ('6', 'games')], max_length=5),
        ),
    ]
