# Generated by Django 2.1.5 on 2019-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190620_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_image'),
        ),
    ]
