# Generated by Django 2.1.5 on 2019-06-25 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(blank=True, max_length=500)),
                ('hobbies', models.CharField(blank=True, max_length=500)),
                ('music', models.CharField(blank=True, max_length=500)),
                ('movies', models.CharField(blank=True, max_length=500)),
                ('tv_shows', models.CharField(blank=True, max_length=500)),
                ('games', models.CharField(blank=True, max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
