# Generated by Django 2.1.5 on 2019-07-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190703_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingAndViewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'cancelled')], max_length=50)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewing',
        ),
        migrations.AddField(
            model_name='viewingandviewers',
            name='blog_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewingandviewers',
            name='blog_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
