# Generated by Django 2.1.5 on 2019-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190704_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
