# Generated by Django 2.1.5 on 2019-07-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_ethnicity_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethnicity',
            old_name='ethnicity_name',
            new_name='country_name',
        ),
    ]
