# Generated by Django 2.1.5 on 2019-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190710_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='skype_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
