# Generated by Django 2.1.5 on 2019-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_usercontactinfo_skype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality_key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
