# Generated by Django 2.1.5 on 2019-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_nationality_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private_account',
            field=models.BooleanField(default=False),
        ),
    ]
