# Generated by Django 2.1.5 on 2019-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190718_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message_privacy',
            field=models.CharField(choices=[('1', 'your viewers'), ('2', 'viewers you view'), ('3', 'off')], default='1', max_length=20),
        ),
    ]
