# Generated by Django 2.1.5 on 2019-08-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_viewingandviewers_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='accounts.ViewingAndViewers'),
        ),
        migrations.AddField(
            model_name='user',
            name='viewing',
            field=models.ManyToManyField(blank=True, related_name='viewing', to='accounts.ViewingAndViewers'),
        ),
    ]
