# Generated by Django 2.1.5 on 2019-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20190809_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingandviewers',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'cancelled')], default='1', max_length=50),
        ),
    ]
