# Generated by Django 2.1.5 on 2019-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190809_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewingandviewers',
            old_name='accepted_date',
            new_name='action_date',
        ),
    ]
